import React, { useMemo, useState } from 'react';
import { lessons, timeline, quiz } from './data/content.js';
import { chatWithAI } from './services/api.js';

const navItems = [['home','Trang chủ'],['library','Thư viện'],['timeline','Timeline'],['ai','AI trợ giảng'],['dashboard','Tiến độ']];

function Card({ lesson }) {
  return <article className="card"><div className="icon">{lesson.icon}</div><span className="tag">{lesson.tag}</span><h3>{lesson.title}</h3><p>{lesson.desc}</p><button className="secondary" onClick={() => alert(`Mở bài học: ${lesson.title}`)}>Xem bài →</button></article>;
}

function Home({ setView }) {
  return <section className="view active">
    <div className="hero"><div className="heroText"><div className="eyebrow">Học tập • Khám phá • AI</div><h1>Lịch sử Toán học<br/><em>trở nên sống động.</em></h1><p>Khám phá những câu chuyện phía sau các con số, công thức và phát minh. Học sinh có thể xem học liệu, nghiên cứu nhân vật, hỏi AI và kiểm tra kiến thức sau mỗi bài.</p><div className="actions"><button className="primary" onClick={() => setView('library')}>Bắt đầu khám phá →</button><button className="secondary" onClick={() => setView('ai')}>Hỏi AI</button></div></div><div className="heroCard"><div><span className="tag">Bài học nổi bật</span><h2>Toán học qua các nền văn minh</h2><p className="muted">Từ Ai Cập, Hy Lạp đến những đóng góp làm thay đổi Toán học hiện đại.</p></div><div className="orb"/><div className="mini"><Stat value="12" label="chủ đề"/><Stat value="24" label="bài học"/><Stat value="AI" label="trợ giảng"/></div></div></div>
    <div className="section"><div className="sectionHead"><div><h2>Học liệu nổi bật</h2><div className="muted">Nội dung được tổ chức để học sinh dễ tìm và dễ học.</div></div></div><div className="grid">{lessons.slice(0,3).map(l => <Card key={l.title} lesson={l}/>)}</div></div>
  </section>;
}
function Stat({value,label}) { return <div className="stat"><b>{value}</b><small>{label}</small></div>; }
function Library() { const [q,setQ]=useState(''); const filtered=useMemo(()=>lessons.filter(x=>`${x.title} ${x.desc} ${x.key}`.toLowerCase().includes(q.toLowerCase())),[q]); return <section className="view active"><Header title="Thư viện lịch sử Toán học" text="Tìm kiếm bài học, nhà toán học và chủ đề."/><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="🔎 Tìm kiếm: Euclid, Ai Cập, số học..."/><button className="primary">Tìm</button></div>{filtered.length?<div className="grid">{filtered.map(l=><Card key={l.title} lesson={l}/>)}</div>:<Empty text="Không tìm thấy học liệu phù hợp."/>}</section>; }
function Header({title,text}) { return <div className="sectionHead"><div><h2>{title}</h2><div className="muted">{text}</div></div></div>; }
function Empty({text}) { return <div className="card empty">{text}</div>; }
function TimelineView(){ return <section className="view active"><Header title="Dòng thời gian" text="Một cách trực quan để khám phá sự phát triển của Toán học."/><div className="timeline">{timeline.map(([year,name,desc])=><div className="time" key={name}><strong>{year}</strong><h3>{name}</h3><p className="muted">{desc}</p></div>)}</div><div className="section"><div className="card"><span className="tag">Nghiên cứu có trách nhiệm</span><h3>Kiểm chứng trước khi tin</h3><p>AI có thể hỗ trợ tìm hiểu và trình bày, nhưng nội dung lịch sử cần được đối chiếu với các nguồn uy tín.</p></div></div></section>; }
function AIView(){ const [messages,setMessages]=useState([{role:'bot',text:'Xin chào! Mình có thể giúp bạn giải thích một chủ đề lịch sử Toán, tóm tắt bài học hoặc tạo câu hỏi ôn tập.'}]); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); async function ask(){const v=input.trim();if(!v||loading)return;setMessages(m=>[...m,{role:'me',text:v}]);setInput('');setLoading(true);try{const data=await chatWithAI(v);setMessages(m=>[...m,{role:'bot',text:data.answer||'Backend chưa trả về câu trả lời.'}]);}catch{setMessages(m=>[...m,{role:'bot',text:'Bản demo chưa kết nối AI backend. Hãy cấu hình VITE_API_BASE_URL và endpoint /api/ai/chat để sử dụng AI thật.'}]);}finally{setLoading(false)}} return <section className="view active"><Header title="AI trợ giảng" text="Đặt câu hỏi để hiểu bài theo cách đơn giản hơn."/><div className="ai"><div className="chat"><div className="messages">{messages.map((m,i)=><div className={`bubble ${m.role}`} key={i}>{m.text}</div>)}{loading&&<div className="bubble bot">Đang suy nghĩ…</div>}</div><div className="chatbar"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Hỏi về lịch sử Toán..."/><button className="primary" onClick={ask}>Gửi</button></div></div><div className="card"><span className="tag">Các chức năng</span><h3>AI học cùng bạn</h3><p>• Giải thích khái niệm<br/>• Tóm tắt bài học<br/>• Tạo câu hỏi luyện tập<br/>• Gợi ý nghiên cứu<br/>• Phân tích câu trả lời sai<br/>• Gợi ý bài học tiếp theo</p><hr/><p className="muted">API key không đặt trong trình duyệt; AI sẽ được gọi qua backend.</p></div></div></section>; }
function Dashboard(){const [selected,setSelected]=useState(null);const [submitted,setSubmitted]=useState(false);return <section className="view active"><Header title="Tiến độ học tập" text="Bảng điều khiển minh họa cho tài khoản học sinh."/><div className="dash"><StatCard label="Bài đã học" value="8"/><StatCard label="Quiz đã làm" value="6"/><StatCard label="Điểm trung bình" value="86%"/><StatCard label="Chuỗi học" value="4 ngày"/></div><div className="section"><div className="card"><h3>Tiến độ khóa khám phá</h3><div className="progress"><i/></div><p className="muted">62% · Bài tiếp theo: “Toán học Hy Lạp cổ đại”</p></div></div><div className="section"><div className="quiz"><span className="tag">Quiz mẫu</span><h3>{quiz.question}</h3>{quiz.options.map((x,i)=><button key={x} className={`option ${selected===i?'selected':''}`} onClick={()=>setSelected(i)}>{String.fromCharCode(65+i)}. {x}</button>)}<button className="primary" onClick={()=>setSubmitted(true)}>Nộp bài</button>{submitted&&<p className="result">{selected===quiz.answer?'✅ Chính xác!':'ℹ️ Đáp án đúng trong quiz mẫu: Euclid.'}</p>}</div></div></section>;}
function StatCard({label,value}){return <div className="card"><small className="muted">{label}</small><b className="big">{value}</b></div>}
function App(){const [view,setView]=useState('home');const content={home:<Home setView={setView}/>,library:<Library/>,timeline:<TimelineView/>,ai:<AIView/>,dashboard:<Dashboard/>};return <div className="app"><header className="top"><div className="brand"><div className="logo">∑</div><div>MathHistory <span>AI</span></div></div><nav>{navItems.map(([id,label])=><button key={id} onClick={()=>setView(id)} className={view===id?'active':''}>{label}</button>)}</nav><button className="profile" onClick={()=>alert('Khu vực tài khoản sẽ kết nối backend trong phiên bản production.')}>👤 Học sinh</button></header><main>{content[view]}</main><footer className="footer">MathHistory AI · Prototype giáo dục dựa trên ý tưởng “Sử dụng AI hỗ trợ học sinh nghiên cứu lịch sử Toán”.</footer></div>}
export default App;
